name: Node.js CI

on:
  push:
    branches: 
      - develop
  pull_request:
    branches: 
      - master
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
        - 5432:5432
        
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - run: npm test
      env:
        POSTGRES_HOST: postgres
        POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
        TEST_POSTGRES_HOST: ${{ job.steps.env.POSTGRES_HOST }}
        TEST_POSTGRES_DATABASE: postgres
        TEST_POSTGRES_USERNAME: postgres
        TEST_POSTGRES_PASSWORD: postgres

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        CI: true
